using z1.Model;
//Паттерн Состояние
Document doc = new Document("У себя", "Дождались меня белые ночи\r\nНад простором густых островов…\r\nСнова смотрят знакомые очи,\r\nИ мелькает былое без слов.");
Console.WriteLine(doc);
Console.WriteLine();
doc.ToPublish();
Console.WriteLine();
Console.WriteLine(doc);
Console.WriteLine();
doc.ToPublish();
Console.WriteLine();
Console.WriteLine(doc);
Console.WriteLine();
doc.ToPublish();
Console.WriteLine();
Console.WriteLine(doc);
Console.WriteLine();
doc.LowerState();
Console.WriteLine();
Console.WriteLine(doc);
Console.WriteLine();
doc.LowerState();
Console.WriteLine();
Console.WriteLine(doc);
Console.WriteLine();
doc.LowerState();
Console.WriteLine();
